formatter: markdown table

content: |-
  ## Example

  ```hcl
  {{ include "examples/example.com/main.tf" | replace "./../.." "github.chezmoi.sh/libraries/terraform/dns" }}
  ```

  {{ .Inputs | replace "\"|\"" "\"\\|\"" }}

  {{ .Outputs }}

  {{ .Providers }}

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: required
